# Generated by Django 4.1 on 2022-09-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
