# Generated by Django 4.1 on 2022-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_img', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
